### ISSUE TITLE
Export Invalid .xlsx file in Api only mode

### ISSUE THREAD

**Issue by NickBeukema** [caxlsx/caxlsx_rails#107] opened 2018-09-27 12:53 UTC
I have created a base repo:
https://github.com/NickBeukema/axlsx_rails_testing

For both regular and api only mode, for both have done the following

* Generate App and `Lead` model with properties `Name` and `Occupation`
* Create `LeadsController` with `index` method, add `resources :leads` to routes file
* Create `views/leads/index.xlsx.axlsx` file for rendering the `.xlsx` file

I visit the url and the api only version exports the file as 1 byte and cannot be opened, while the non api only version exports the excel file normally.

To reproduce the two repos, do the following:

1. Clone and bundle
2. `rails db:migrate db:seed`
3. `rails s`
4. Visit `localhost:3000/leads.xlsx`

I've also added a `json` responder to assure that the data is there and the `respond_to` function is working, so you can visit `localhost:3000/leads.json` to see the json data.

Do you know what dependencies I'm missing in the api only version? I've already included `ActionController::MimeResponds` to allow for `respond_to` usage. Any help would be great!

**Comment by straydogstudio** [comment] 2018-09-27 13:12
Thanks! I'll take a look. I don't remember the differences off the top of my head.

**Comment by straydogstudio** [comment] 2018-10-04 04:27
Also I notice the api is rails 5.1.4 and the regular is 5.2.1. Did you just create a generic api?

**Comment by fresh2nd** [comment] 2018-10-16 16:33
Same issue here. Do you know what we need to add?

**Comment by NickBeukema** [comment] 2018-10-16 17:36
For now I just made my `application_controller.rb` class inherit from `ActionController::Base` instead of `ActionController::API`.

From

    class ApplicationController < ActionController::API
    ...

to

    class ApplicationController < ActionController::Base
    ...

**Comment by straydogstudio** [comment] 2018-10-16 18:27
I’ve spent a few hours in this. Hopefully I will get some more time this week. It is deep in the inheritance tree.

**Comment by straydogstudio** [comment] 2018-10-27 15:57
@NickBeukema @fresh2nd 
As I expected, Rails in API mode does not include the template loading mechanism. This is by design of course, since api does not include ActionView. See the difference in render_to_body between [action_view/rendering.rb](https://github.com/rails/rails/blob/master/actionview/lib/action_view/rendering.rb#L82-L85) and [action_controller/api/api_rendering.rb](https://github.com/rails/rails/blob/master/actionpack/lib/action_controller/api/api_rendering.rb#L11-L14). 

I would do one of two things:
* If the templates aren't shared with another application, I would enclose the template code in a helper object and use it to produce the spreadsheet and stream it. You can see [the code that is wrapped around the template here](https://github.com/straydogstudio/axlsx_rails/blob/master/lib/axlsx_rails/template_handler.rb#L16-L25). Then I would simply serve the result from the controller. 
* If the templates have to be shared, I would try to adapt [this script example](https://gist.github.com/straydogstudio/323139591f2cc5d48fbc) and see if I could adapt it. That shows what must be included. 

If either of you do so, consider adding a pull request for the README. Or drop it here. I will do it at some point.

**Comment by DonaldChiang** [comment] 2018-12-02 09:12
Based on this issue: https://github.com/rails/rails/issues/27211
Override render_to_body method in your API mode controller

```ruby
class TestController < ActionController::API
  include ActionView::Rendering

  def show
    respond_to do |format|
      format.xlsx
    end
  end

  private

  def render_to_body(options)
    _render_to_body_with_renderer(options) || super
  end
end
```

And now you can export correct xlsx file, but still need better solution here.

**Comment by straydogstudio** [comment] 2019-11-15 18:12
@DonaldChiang Did you ever find a better solution? What kind of solution were you imagining?

**Comment by straydogstudio** [comment] 2020-02-07 08:00
Closing after adding this to the readme.

**Closed by straydogstudio** 2020-02-07 08:00 UTC

**Comment by straydogstudio** [comment] 2020-04-21 21:30
There is another possibility. If you only have a Rails API, you really don't need to organize the code in templates. Instead consider using service classes to organize your code. Or something similar.
